### ISSUE TITLE
Error of "Face_regisration"

### ISSUE THREAD

**Issue by a5111295** [Ignitarium-Renesas/RZV2L_AiLibrary#11]
Hello ,

I used latest Face_regisration of 06-Face_recognition_spoof_detection spoof_detection.

but there is the below error.
"VIDIOC_STREAMON: Broken pipe"

could you please fit it?

**Comment by mohitb-ign** [comment]
We are unable to reproduce the issue. 
Can you please share the steps to reproduce it?

**Comment by a5111295** [comment]
thank you for your response.
this is Face_registration_usbcam/exe
![image](https://github.com/Ignitarium-Renesas/RZV2L_AiLibrary/assets/130450327/356a48e1-bbdc-47fb-9bd0-6040cbfd4957)

**Comment by mohitb-ign** [comment]
1. Thanks for the screenshot. We were able to reproduce the issue with this.
2. The issue is observed because of openCV' function [VideoCapture](https://github.com/Ignitarium-Renesas/RZV2L_AiLibrary/blob/3f54b8ac5b29e54792d1bfb28e71bb805c17d5e0/06_Face_recognition_spoof_detection/Face_registration_usbcam/src/capture_face.cpp#L86C9-L86C9) not getting the feed from USB camera. (Click on the link to view the source code).
3.  This issue needs to be fixed by an end user. The output below shows that both USB and Coral cameras are connected to the board at the same time.
```
root@smarc-rzv2l:~/Face_registration_usbcam/exe# v4l2-ctl --list-devices
RZG2L_CRU (platform:10830000.video):
    /dev/video0
    /dev/media0
 
UVC Camera (046d:0825) (usb-11c70100.usb-1.4):
    /dev/video1
    /dev/video2
    /dev/media1
```

5. In this case, an error will be observed. To fix the error, and to get the feed from USB camera, user should modify the `VideoCapture cap(0)` to `VideoCapture cap(1)` in file 06_Face_recognition_spoof_detection/Face_registration_usbcam/src/capture_face.cpp. Re-building of the application is required after this source code modification.

**Comment by a5111295** [comment]
Thank you for your reply.

I checked USB camera only. therefore there were no errors.
in this directory, USB camera mode is assumed, there are no issues.

thank you
